task:
  freebsd_instance:
    cpu: 4
    memory: 16G
    matrix:
      - image_family: freebsd-13-1
      # image_family: freebsd-14-0-snap

  env:
    CIRRUS_CLONE_DEPTH: 1
    GITHUB_TOKEN: ENCRYPTED[a04e79244ec3fcc3460b75831aed2f0b80d92fbd74721d8cb40799b9ba1c2d94d5d9bfee7d3fc73cdfe8f35740ef6fdf]

  furybsd_cache:
    folder: /usr/local/furybsd/amd64/cache/

  auto_cancellation: false
  stateful: false
  timeout_in: 60m
  # only_if: $CIRRUS_TAG !=~ 'continuous.*'
  # Do not build tags, only commits
  only_if: $CIRRUS_TAG !=~ '..*'

  env:
    matrix:
      DESKTOP: 'hello'

  env:
    matrix:
      arch: 'amd64'

  Environment_script:
    # sed -i '' -e 's|quarterly|release_1|g' "${uzip}/etc/pkg/FreeBSD.conf"
    - rm -f /usr/local/furybsd/amd64/cache/packages/transient/* || true # Don't cache transient pkg
    - env
    - kldload zfs.ko || true
    - kldload tmpfs.ko || true
    - kldload nullfs.ko || true
    - kldload geom_uzip.ko || true
    # As of FreeBSD 13.1, sha is in base and the sha package is no longer built
    - pkg install -y pkg git-lite zsync wget bash zip devel/py-xdg librsvg2 ca_root_nss # qemu-devel uefi-edk2-qemu-x86_64
    - mkdir -p /usr/local/furybsd/uzip /usr/local/furybsd/cdroot/
    - mount -t tmpfs tmpfs /usr/local/furybsd/uzip
    - mount -t tmpfs tmpfs /usr/local/furybsd/cdroot/
    
  Build_script:
    - export VER=$(uname -r | cut -d "-" -f 1)
    # if [ "$VER" = "12.1" ] ; then export PERSIST_NEW_BUILDNUMBER="YES" ; fi # Only persist incremented build number for one of the builds in the matrix
    - export PERSIST_NEW_BUILDNUMBER="YES"
    - wget -c -q https://github.com/helloSystem/buildnumbers/releases/download/initial/buildnumbers
    - chmod +x ./buildnumbers
    - export BUILDNUMBER=$(RELEASE_ID_FOR_STORAGE=33980128 ./buildnumbers)
    - /bin/sh -x ./build.sh "${DESKTOP}" || true # FIXME: Why does this return an error even though the ISO succeeded?
    - df -h
    - ls -lh /usr/local/furybsd/iso/*.iso || false # Error out if ISO was not produced to mitigate the above
    # ( cd /usr/local/furybsd/ ; zsyncmake *.iso )
    - rm -f /usr/local/furybsd/amd64/cache/packages/transient/* || true # Don't cache transient pkg
    
  Upload_script:
    - export VER=$(uname -r | cut -d "-" -f 1) # No way to pass on from Build_script to Upload_script?
    - ls -lh /usr/local/furybsd/iso/
    - case "$CIRRUS_BRANCH" in *pull/*) echo skipping since PR ;; * ) wget -c -q https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; ./ghr -prerelease -delete -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -b "This is an __experimental build__ for __developers__ and __testers__. Regular users should get the latest released version instead." -c "${CIRRUS_CHANGE_IN_REPO}" "${CIRRUS_BRANCH}"-"${VER}" /usr/local/furybsd/iso/ ; esac
